
name: Build and Publish Docker Image to Docker hub

on:
  workflow_dispatch:
      inputs:
        environment:
            description: 'Environment to run'
            type: choice
            required: true
            default: "DEV"
            options: ["DEV", "STAGE", "PROD"]

        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options: ["info", "warning", "debug"]

        tag:
          description: 'Tag version'
          required: true
          default: 'lastest'
          type: string
env:
  level: ${{ inputs.logLevel }}
  environment: ${{ inputs.environment }}
  tag: ${{ inputs.tag }}
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting"
        run: |
          echo "USERNAME: ${{ github.actor }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "logLevel: ${{ github.event.inputs.logLevel }}" 

      - name: Checkout code
        uses: actions/checkout@v2


  context-env-dev:
    if: ${{ inputs.environment== 'DEV' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app dev
        run: npm run-script deploy-dev

  context-env-stage:
    if: ${{ inputs.environment== 'STAGE' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Angular app stage
        run: npm run-script deploy-stage

  context-env-prod:
    if: ${{ inputs.environment== 'PROD' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Angular app prod
        run: npm run-script deploy-prod

  build-image-docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Build Docker image
        run: |
          docker build -t my-angular-app .
          docker tag my-angular-app jsilvazuniga/my-angular-app:${{ env.environment }}.${{ env.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push jsilvazuniga/my-angular-app:${{ env.environment }}.${{ env.tag }}