name: Build and Deploy
run-name: Build and Deploy Angular application
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run
        type: choice
        required: true
        default: DEV
        options:
          - DEV
          - VAL
          - PROD
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug
permissions:
  contents: write
jobs:
  build-and-deploy-app:
    name: >-
      Build ${{ inputs.environment }} Level ${{ inputs.logLevel }} por ${{
      github.actor }}
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
      LOG_LEVEL: ${{ inputs.logLevel }}
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - run: |
          echo "USERNAME: $USERNAME"
          echo "Environment: $LOG_LEVEL"
          echo "logLevel: $ENVIRONMENT"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        if: ${{ env.ENVIRONMENT == 'PROD' }}
        run: |
          npm ci 
          npm run-script deploy-prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: build