
name: Build and Publish Docker Image to Docker hub

on:
  workflow_dispatch:
      inputs:
        environment:
            description: 'Environment to run'
            type: choice
            required: true
            default: "DEV"
            options: ["DEV", "STAGE", "PROD"]

        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options: ["info", "warning", "debug"]

        tag:
          description: 'Tag version'
          required: true
          default: 'lastest'
          type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting"
        run: |
          echo "USERNAME: ${{ github.actor }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "logLevel: ${{ github.event.inputs.logLevel }}" 
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run-script deploy-prod

      - name: Build Docker image
        run: |
          docker build -t my-angular-app .
          docker tag my-angular-app jsilvazuniga/my-angular-app:${{ inputs.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push jsilvazuniga/my-angular-app:${{ inputs.tag }}